### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by danigalindo10**
### List Structure ✅ ✅ ✅ 
For this project I:
- Set up a new project with webpack that is based on my previous webpack exercise completed.
- Created an index.js file and set an array of some simple to-do tasks (array of objects). Each task object contains three keys:
   1. description [string].
   2. completed [bool].
   3. index: [number].
- Wrote a function to iterate over the tasks array and populate an HTML list item element for each task.
- Created a style.css and set rules for the To-Do List. CSS is loaded by Webpack Style/CSS Loader.

### CODE REVIEW

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @danigalindo10 🙋‍♀️,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project, that is not documented. Please update your README and make it relevant to this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @danigalindo10 ,  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- All the functionality works as expected ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 


giphy

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### **STATUS: APPROVED  ✔️** 
------
Hi STUDENT,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 


giphy

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danigalindo10** [comment]
Hello, @ShoiraTa hope you are having a good week. 
When I am trying to submit my project, in my dashboard appears that I have to request another review. Please could you help me with that?

**Comment by danigalindo10** [comment]
# 🔴 🔴 🔴 To the reviewer 🔴 🔴 🔴 
Dear code reviewer, I got my project approved by my previous code reviewer, but I couldn't reach her to change my submission status. Please, take this into account.

**Comment by KDlamini** [comment]
@danigalindo10,

I will approve your project on the dashboard. 👍🏾 
We apologize for any inconvenience. 🙏🏾 

Cheers 🥂  and happy coding 👏🏾

**Comment by KDlamini** [comment]
> Hello, @ShoiraTa hope you are having a good week. When I am trying to submit my project, in my dashboard appears that I have to request another review. Please could you help me with that?

Noted...

**Comment by ShoiraTa** [comment]
Hello, @danigalindo10  Sorry for late response, but I am sure I approved your project maybe some bug occurred 😢 
Can you submit it by now?

**Comment by danigalindo10** [comment]
Hello @ShoiraTa,
Yes, I could submit it properly. Thank you anyway for your response. 🙂

**Pull request merged**
